
global_frame: map
robot_base_frame: base_footprint
rolling_window: false
track_unknown_space: false
width: 7
height: 7
robot_radius: 0.25
update_frequency: 10
publish_frequency: 5

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser,         type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}

inflation:
  inflation_radius: 0.1
  cost_scaling_factor: 0.1



# global_costmap:
#   #Set the global and robot frames for the costmap
#   global_frame: map
#   robot_base_frame: base_footprint

#   #Set the update and publish frequency of the costmap
#   update_frequency: 5.0
#   publish_frequency: 2.0

#   #We'll use a map served by the map_server to initialize this costmap
#   static_map: true
#   rolling_window: false

#   footprint_padding: 0.02