robot_radius: 0.30
footprint_padding: 0.02
robot_base_frame: base_footprint
update_frequency: 3.0
publish_frequency: 2.0
transform_tolerance: 1.0
publish_voxel_map: false
resolution: 0.1 

obstacle_range: 5.5
raytrace_range: 8.0
static:
  map_topic: map
  subscribe_to_updates: true
  lethal_cost_threshold: 50

obstacles_laser:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
  inflation_radius: 0.20
  cost_scaling_factor: 0.1